source $HOME/MENU-TMX/BOT/color.sh

echo -e ${azul} "	                   ug			"
echo -e ${azul} "                       b			"
echo -e ${azul} "                      g           bug		"
echo -e ${azul} "                      u        bug		"
echo -e ${azul} "      bugbug          b       g			"
echo -e ${azul} "            bug      bugbug bu			"
echo -e ${azul} "               bug  bugbugbugbugbugbug		"
echo -e ${azul} "  bug   bug   bugbugbugbugbugbugbugbugb		"
echo -e ${azul} "     bug${rojo}•#•${azul}bug bugbugbugbugbugbugbugbugbu	"
echo -e ${azul} "   bugbugbugbu gbugbugbugbugbugbugbugbugbu	"
echo -e ${azul} "  bugbugbugbug		${verde}{${blanco}MENU-TMX${verde}} ${azul}				"
echo -e ${azul} "   bugbugbugbu gbugbugbugbugbugbugbugbugbu	"
echo -e ${azul} "     bug${rojo}•#•${azul}bug bugbugbugbugbugbugbugbugbu   ${EAM}Created by:@Hacking-Eam${azul}"
echo -e ${azul} "  bug   bug  gbugbugbugbugbugbugbugbugb     ${EAM}facebook  :Edison Antil${azul}"
echo -e ${azul} "               bug  bugbugbugbugbugbug	     ${EAM}instagram :@_edis_962_a_${azul}"
echo -e ${azul} "            bug      bugbug  bu			"
echo -e ${azul} "      bugbug          b        g		"
echo -e ${azul} "                      u         bug		"
echo -e ${azul} "                      g            bug		"
echo -e ${azul} "                       b			"
echo -e ${azul} "                        ug			"

